# Generated by Django 6.0.6 on 2026-06-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=250, verbose_name='Title (AR)')),
                ('title_en', models.CharField(max_length=250, verbose_name='Title (EN)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title (AR)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=250, verbose_name='Title (AR)')),
                ('title_en', models.CharField(max_length=250, verbose_name='Title (EN)')),
                ('content_ar', models.TextField(verbose_name='Content (AR)')),
                ('content_en', models.TextField(verbose_name='Content (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Image')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title (AR)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('content_ar', models.TextField(verbose_name='Content (AR)')),
                ('content_en', models.TextField(verbose_name='Content (EN)')),
                ('slug', models.SlugField(help_text='Short URL identifier, e.g. "about-us"', max_length=100, unique=True, verbose_name='URL Slug')),
                ('show_in_nav', models.BooleanField(default=True, verbose_name='Show in Navbar')),
                ('nav_order', models.PositiveIntegerField(default=0, help_text='Lower number = appears first', verbose_name='Navbar Order')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['nav_order', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name_ar', models.CharField(max_length=200, verbose_name='Member Name (AR)')),
                ('member_name_en', models.CharField(max_length=200, verbose_name='Member Name (EN)')),
                ('content_ar', models.TextField(verbose_name='Content (AR)')),
                ('content_en', models.TextField(verbose_name='Content (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Image')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='Name (AR)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (EN)')),
                ('role_ar', models.CharField(max_length=200, verbose_name='Role (AR)')),
                ('role_en', models.CharField(max_length=200, verbose_name='Role (EN)')),
                ('bio_ar', models.TextField(blank=True, verbose_name='Bio (AR)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Bio (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Image')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
