# Generated by Django 6.0.6 on 2026-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title (AR)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('subtitle_ar', models.TextField(blank=True, verbose_name='Subtitle (AR)')),
                ('subtitle_en', models.TextField(blank=True, verbose_name='Subtitle (EN)')),
                ('image', models.ImageField(help_text='Recommended: 1600 × 900 px or wider', upload_to='hero/', verbose_name='Background Image')),
                ('cta1_text_ar', models.CharField(blank=True, max_length=100, verbose_name='Button 1 Text (AR)')),
                ('cta1_text_en', models.CharField(blank=True, max_length=100, verbose_name='Button 1 Text (EN)')),
                ('cta1_url', models.CharField(blank=True, help_text='Full path e.g. /ar/contact/ — leave blank for Contact page', max_length=200, verbose_name='Button 1 URL')),
                ('cta2_text_ar', models.CharField(blank=True, max_length=100, verbose_name='Button 2 Text (AR)')),
                ('cta2_text_en', models.CharField(blank=True, max_length=100, verbose_name='Button 2 Text (EN)')),
                ('cta2_url', models.CharField(blank=True, help_text='Full path e.g. /ar/team/ — leave blank for Team page', max_length=200, verbose_name='Button 2 URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = appears first', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat1_number', models.CharField(default='1,000+', max_length=20, verbose_name='Stat 1 — Number')),
                ('stat1_label_ar', models.CharField(default='طالب ملتحق', max_length=100, verbose_name='Stat 1 — Label (AR)')),
                ('stat1_label_en', models.CharField(default='Students Enrolled', max_length=100, verbose_name='Stat 1 — Label (EN)')),
                ('stat2_number', models.CharField(default='15+', max_length=20, verbose_name='Stat 2 — Number')),
                ('stat2_label_ar', models.CharField(default='لغة مُدرَّسة', max_length=100, verbose_name='Stat 2 — Label (AR)')),
                ('stat2_label_en', models.CharField(default='Languages Taught', max_length=100, verbose_name='Stat 2 — Label (EN)')),
                ('stat3_number', models.CharField(default='20+', max_length=20, verbose_name='Stat 3 — Number')),
                ('stat3_label_ar', models.CharField(default='برنامج متاح', max_length=100, verbose_name='Stat 3 — Label (AR)')),
                ('stat3_label_en', models.CharField(default='Programs Offered', max_length=100, verbose_name='Stat 3 — Label (EN)')),
                ('stat4_number', models.CharField(default='400+', max_length=20, verbose_name='Stat 4 — Number')),
                ('stat4_label_ar', models.CharField(default='خريج', max_length=100, verbose_name='Stat 4 — Label (AR)')),
                ('stat4_label_en', models.CharField(default='Alumni', max_length=100, verbose_name='Stat 4 — Label (EN)')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
