# Generated by Django 6.0.6 on 2026-06-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_heroslide_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_address_ar',
            field=models.CharField(blank=True, default='نابلس، الضفة الغربية، فلسطين', max_length=300, verbose_name='Address (AR)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_address_en',
            field=models.CharField(blank=True, default='Nablus, West Bank, Palestine', max_length=300, verbose_name='Address (EN)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, default='lrc@najah.edu', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, default='+970 9 234 5113', max_length=50, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Leave blank to hide the icon', verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_desc_ar',
            field=models.TextField(blank=True, default='تعزيز تعلّم اللغات وتبادل الثقافات في جامعة النجاح الوطنية، نابلس، فلسطين.', verbose_name='Footer Description (AR)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_desc_en',
            field=models.TextField(blank=True, default='Promoting language learning and cultural exchange at An-Najah National University, Nablus, Palestine.', verbose_name='Footer Description (EN)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Leave blank to hide the icon', verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Leave blank to hide the icon', verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Leave blank to hide the icon', verbose_name='YouTube URL'),
        ),
    ]
