# Generated by Django 6.0.6 on 2026-06-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitesetting_contact_address_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Full-width hero image. Recommended: 1400 × 600 px', null=True, upload_to='pages/', verbose_name='Banner Image'),
        ),
    ]
