# Generated by Django 6.0.6 on 2026-06-21 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_page_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title (AR)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('subtitle_ar', models.CharField(blank=True, max_length=300, verbose_name='Subtitle (AR)')),
                ('subtitle_en', models.CharField(blank=True, max_length=300, verbose_name='Subtitle (EN)')),
                ('content_ar', models.TextField(verbose_name='Content (AR)')),
                ('content_en', models.TextField(verbose_name='Content (EN)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Event Date')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Slug')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.event')),
            ],
            options={
                'verbose_name': 'Event Image',
                'verbose_name_plural': 'Event Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sponsor Name')),
                ('logo', models.ImageField(upload_to='sponsors/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, verbose_name='Website')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='main.event')),
            ],
            options={
                'verbose_name': 'Event Sponsor',
                'verbose_name_plural': 'Event Sponsors',
                'ordering': ['order'],
            },
        ),
    ]
