# Generated by Django 6.0.6 on 2026-06-21 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_eventimage_eventsponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stat1_label_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat 1 Label (AR)'),
        ),
        migrations.AddField(
            model_name='event',
            name='stat1_label_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat 1 Label (EN)'),
        ),
        migrations.AddField(
            model_name='event',
            name='stat1_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Stat 1 Number'),
        ),
        migrations.AddField(
            model_name='event',
            name='stat2_label_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat 2 Label (AR)'),
        ),
        migrations.AddField(
            model_name='event',
            name='stat2_label_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat 2 Label (EN)'),
        ),
        migrations.AddField(
            model_name='event',
            name='stat2_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Stat 2 Number'),
        ),
        migrations.AddField(
            model_name='event',
            name='stat3_label_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat 3 Label (AR)'),
        ),
        migrations.AddField(
            model_name='event',
            name='stat3_label_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat 3 Label (EN)'),
        ),
        migrations.AddField(
            model_name='event',
            name='stat3_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Stat 3 Number'),
        ),
        migrations.AddField(
            model_name='event',
            name='stat4_label_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat 4 Label (AR)'),
        ),
        migrations.AddField(
            model_name='event',
            name='stat4_label_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat 4 Label (EN)'),
        ),
        migrations.AddField(
            model_name='event',
            name='stat4_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Stat 4 Number'),
        ),
        migrations.CreateModel(
            name='EventQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.TextField(verbose_name='Quote (AR)')),
                ('text_en', models.TextField(verbose_name='Quote (EN)')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Author Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='main.event')),
            ],
            options={
                'verbose_name': 'Event Quote',
                'verbose_name_plural': 'Event Quotes',
                'ordering': ['order'],
            },
        ),
    ]
