# Generated by Django 6.0.6 on 2026-07-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_stat1_label_ar_event_stat1_label_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sponsor Name')),
                ('logo', models.ImageField(upload_to='sponsors/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, verbose_name='Website')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='main.sponsor', verbose_name='Sponsors'),
        ),
        migrations.DeleteModel(
            name='EventSponsor',
        ),
    ]
