# Generated by Django 6.0.6 on 2026-07-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sponsor_model_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Section Title (AR)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Section Title (EN)')),
                ('content_ar', models.TextField(verbose_name='Content (AR)')),
                ('content_en', models.TextField(verbose_name='Content (EN)')),
                ('icon', models.CharField(blank=True, help_text='e.g. bi-star-fill, bi-globe2, bi-people-fill', max_length=60, verbose_name='Bootstrap Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.event')),
            ],
            options={
                'verbose_name': 'Event Section',
                'verbose_name_plural': 'Event Sections',
                'ordering': ['order'],
            },
        ),
    ]
