# Generated by Django 6.0.6 on 2026-07-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content_ar',
            field=models.TextField(blank=True, verbose_name='Content (AR)'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Content (EN)'),
        ),
    ]
